general.import = [ "./themes/themes/gruvbox_material.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold   = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
size = 10

[window]
padding = { x = 14, y = 14 }
decorations = "None"
opacity = 1   # or background_opacity if using newer Alacritty

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]

